# Generated by Django 3.2.5 on 2021-07-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrosbestsellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('em_estoque', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
